// <auto-generated />
namespace iSmileAlignerTS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m201510192 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m201510192));
        
        string IMigrationMetadata.Id
        {
            get { return "201510191159597_m20151019-2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
