// <auto-generated />
namespace iSmileAlignerTS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m201510291 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m201510291));
        
        string IMigrationMetadata.Id
        {
            get { return "201510291409536_m20151029-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
