// <auto-generated />
namespace iSmileAlignerTS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m201602103 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m201602103));
        
        string IMigrationMetadata.Id
        {
            get { return "201602101053369_m201602103"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
