// <auto-generated />
namespace iSmileAlignerTS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m20171122attachment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m20171122attachment));
        
        string IMigrationMetadata.Id
        {
            get { return "201711221138430_m20171122attachment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
